version: '3.8'

services:
  postgres:
    image: postgres:latest
    env_file:
      - .env
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
    ports:
      - "${DATABASE_PORT}:5432"

  db-starter:
    image: db-starter:1.0
    env_file:
      - .env
    depends_on:
      - postgres
    restart: "no"
    #command: ["npx", "ts-node", "src/init-db.ts"]
    
  transaction-service:
    image: transaction-service:0.1
    env_file:
      - .env
    depends_on:
      db-starter:
        condition: service_completed_successfully
    ports:
    - "${TRANSACTION_PORT}:5051"
