version: '3.8'

services:
  postgres:
    image: postgres:latest
    env_file:
      - .env
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
    ports:
      - "${DATABASE_PORT}:5432"  # Используем порт 5432 для PostgreSQL

  db-starter:
    build:
      context: ../db-starter
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - postgres  # Исправлено имя сервиса на postgres
    command: ["ts-node", "src/init-db.ts"]
